
[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false


[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[font]
size = 14

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window.dimensions]
columns = 140
lines = 30

[mouse]
hide_when_typing = true


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window.padding]
x = 4
y = 4

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "f"
mods = "Control"